name: Test
on:
  push:
    branches: [ develope ]
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
      TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
      TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Install sequlize-cli
        run: npm install sequelize-cli
      - name: Migrate DB
        run: npx sequelize db:migrate --env test_production
      - name: Seed DB
        run: npx sequelize db:seed:all --env test_production
      # - name: Test
      #   run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env: 
      ENV_VARIABLE: TEST
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "secondhand-be-test"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
